# Generated by Django 3.1.13 on 2021-10-26 02:20

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Bean')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Bean URL slug')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country of Origin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Roast URL slug')),
                ('degree', models.CharField(choices=[('cinnamon', 'Cinnamon'), ('city', 'City'), ('city-plus', 'City Plus'), ('full-city', 'Full City'), ('vienna', 'Vienna'), ('espresso', 'Espresso'), ('italian', 'Italian')], max_length=20, verbose_name='Degree of Roast')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by User')),
                ('green_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.bean', verbose_name='Bean')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('method', models.CharField(choices=[('espresso', 'Espresso'), ('v60', 'V60'), ('chemex', 'Chemex')], default='espresso', max_length=20, verbose_name='Method of Extraction')),
                ('grinder', models.CharField(choices=[('niche-zero', 'Niche Zero'), ('baratza_encore', 'Baratza Encore'), ('hario-mini-mill', 'Hario Mini Mill')], default='niche-zero', max_length=20, verbose_name='Grinder')),
                ('grind_setting', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Grinder Coarseness Setting')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperature of Extraction [°C]')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by User')),
                ('roasted_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.roast', verbose_name='Roasted Bean')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
