# Generated by Django 3.1.13 on 2021-10-25 19:02

import autoslug.fields
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2, verbose_name='Country of Origin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bean',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Bean URL slug'),
        ),
    ]
