# Generated by Django 3.1.13 on 2021-11-05 14:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_bean_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='null', editable=False, populate_from='__str__', unique=True, verbose_name='Extraction URL slug'),
            preserve_default=False,
        ),
    ]
