# Generated by Django 3.1.13 on 2021-11-05 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_extraction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='roast_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 5, 17, 15, 4, 537551)),
        ),
    ]
