# Generated by Django 3.1.13 on 2021-11-05 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_roast_roast_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='roast_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 5, 17, 15, 57, 470332, tzinfo=utc)),
        ),
    ]
