# Generated by Django 3.1.13 on 2021-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20211105_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='dose',
            field=models.DecimalField(decimal_places=1, default=24, max_digits=3, verbose_name='Dose Weight [g]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extraction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Extra Notes'),
        ),
    ]
