# Generated by Django 3.1.13 on 2021-11-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_auto_20211107_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='green_weight',
            field=models.IntegerField(default=400, verbose_name='Bean Mass (pre-roast) [g]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roast',
            name='roasted_weight',
            field=models.IntegerField(default=300, verbose_name='Bean Mass (post-roast) [g]'),
            preserve_default=False,
        ),
    ]
