# Generated by Django 3.1.13 on 2021-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_auto_20211107_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast',
            name='green_weight',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Bean Mass (pre-roast) [g]'),
        ),
        migrations.AlterField(
            model_name='roast',
            name='roasted_weight',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Bean Mass (post-roast) [g]'),
        ),
    ]
