# Generated by Django 3.1.13 on 2021-11-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_auto_20211107_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='roast',
            name='current_weight',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5, verbose_name='Current Mass [g]'),
            preserve_default=False,
        ),
    ]
