# Generated by Django 3.1.13 on 2021-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_roast_current_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='grind_setting',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Coarseness'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extraction/'),
        ),
    ]
