# Generated by Django 3.1.13 on 2021-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_extraction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Time of Extraction [s]'),
        ),
    ]
